### ISSUE TITLE
Arkos Tracker 2

### ISSUE THREAD

**Issue by redbug26** [lronaldo/cpctelera#103]
Is Arkos Tracker 2 song supported by cpctelera ?
I couldn't export to bin as described in the documentation

**Comment by lronaldo** [comment]
No, Arkos Tracker 2 is not supported in CPCtelera. As documentation says, CPCtelera only has Arkos Tracker 1 integrated by now. 

However, Arkos Tracker 2 source code is available and some users have just integrated it in their CPCtelera projects, as you can directly add C and assembly files into the src/ folder of any CPCtelera project. As source gets compiled/assembled, you can use Arkos Tracker 2.

Arkos Tracker 2 will be integrated in future versions of CPCtelera.
