### ISSUE TITLE
Files not modified not included in disk

### ISSUE THREAD

**Issue by Arnaud6128** [lronaldo/cpctelera#110]
All files in **dsk directory** that are not modified between two builds are not included in disk.

**Comment by lronaldo** [comment]
Thanks for reporting, @Arnaud6128. This was clearly a bug introduced when we adopted the policy of regenerating DSK completely each time the binary changes. With this policy, dsk/ files have to be also readded each time the DSK is regenerated, but they weren't. The fix has been quite easy, and helpful.

Please, test it to confirm that everything works as expected now.

Thank you very much , @Arnaud6128 :)

**Comment by Arnaud6128** [comment]
All is working.
