### ISSUE TITLE
Image conversion / PNG / wrong palette

### ISSUE THREAD

**Issue by kamelie1706** [lronaldo/cpctelera#112]
Hi,

I do not know if I am doing something wrong but I cannot get the correct colors when using image_conversion using your easy example code.

I have a simple sprite "mouse_left" with only 3 colors (black, grey, white) and a transparent background that I export to PNG according to sRGB from GIMP.
I am targetting Mode 0.

image_conversion.mk
```
PALETTE={0 1 3 4 7 9 10 12 13 16 19 20 21 24 25 26}
$(eval $(call IMG2SPRITES,img/mouse_left.png,0,g,16,32,$(PALETTE),,src/,hwpalette))

```
mouse_left.h
```
// Data created with Img2CPC - (c) Retroworks - 2007-2015
#ifndef _IMG_MOUSE_LEFT_H_
#define _IMG_MOUSE_LEFT_H_

#include <types.h>
extern const u8 g_palette[16];

#define G_MOUSE_LEFT_W 8
#define G_MOUSE_LEFT_H 32
extern const u8 g_mouse_left[8 * 32];

#endif

```
mouse_left.c
```
#include "mouse_left.h"
// Data created with Img2CPC - (c) Retroworks - 2007-2015
// Palette uses hardware values.
const u8 g_palette[16] = { 0x54, 0x44, 0x5c, 0x58, 0x45, 0x56, 0x46, 0x5e, 0x40, 0x47, 0x42, 0x53, 0x5a, 0x4a, 0x43, 0x4b };

// Tile g_mouse_left: 16x32 pixels, 8x32 bytes.

const u8 g_mouse_left[8 * 32] = {
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x01, 0x02, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x01, 0x02, 0x00, 0x00,
	0x00, 0x00, 0x01, 0x03, 0x02, 0x03, 0x00, 0x00,
	0x00, 0x00, 0x01, 0x03, 0x02, 0x03, 0x00, 0x00,
	0x00, 0x01, 0x02, 0x01, 0x02, 0x03, 0x02, 0x00,
	0x00, 0x01, 0x02, 0x01, 0x02, 0x03, 0x02, 0x00,
	0x00, 0x02, 0x02, 0xab, 0x01, 0x03, 0x02, 0x00,
	0x00, 0x02, 0x02, 0xab, 0x01, 0x03, 0x02, 0x00,
	0x01, 0x01, 0x03, 0x03, 0x03, 0x03, 0x03, 0x00,
	0x01, 0x01, 0x03, 0x03, 0x03, 0x03, 0x03, 0x00,
	0x01, 0x01, 0x03, 0x03, 0x03, 0x03, 0x03, 0x00,
	0x01, 0x01, 0x03, 0x03, 0x03, 0x03, 0x03, 0x00,
	0x00, 0x02, 0x02, 0xab, 0x01, 0x03, 0x02, 0x00,
	0x00, 0x02, 0x02, 0xab, 0x01, 0x03, 0x02, 0x00,
	0x00, 0x01, 0x02, 0x01, 0x02, 0x03, 0x02, 0x00,
	0x00, 0x01, 0x02, 0x01, 0x02, 0x03, 0x02, 0x00,
	0x00, 0x00, 0x01, 0x03, 0x02, 0x03, 0x00, 0x00,
	0x00, 0x00, 0x01, 0x03, 0x02, 0x03, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x01, 0x02, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x01, 0x02, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
	0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

```
main.c
```
#include <cpctelera.h>
#include "mouse_left.h"

// Sprite size (in bytes)
#define SP_W   8
#define SP_H   32

// Screen size (in bytes)
#define SCR_W   80
#define SCR_H  200

// Number of loops to wait between each sprite move
#define WAITLOOPS 200

//
// MAIN: Using keyboard to move a sprite example
//
void main(void) {
   u8  x=10, y=10;   // Sprite coordinates
   u8* pvideomem;    // Pointer to video memory
   u32 i;            // 32 bits counter, to let it count passed 65536 (up to 4 Billions)

   //
   // Set up the screen
   //
   // Disable firmware to prevent it from interfering with setPalette and setVideoMode
   cpct_disableFirmware();

   // Set the colour palette
   cpct_fw2hw     (g_palette, 16); // Convert our palette from firmware to hardware colours 
   cpct_setPalette(g_palette, 16); // Set up the hardware palette using hardware colours
   
   // Set video mode 0 (160x200, 16 colours)
   cpct_setVideoMode(0);

   // 
   // Infinite moving loop
   //
   while(1) {
      // Scan Keyboard (fastest routine)
      // The Keyboard has to be scanned to obtain pressed / not pressed status of
      // every key before checking each individual key's status.
      cpct_scanKeyboard_f();

      // Check if user has pressed a Cursor Key and, if so, move the sprite if
      // it will still be inside screen boundaries
      if      (cpct_isKeyPressed(Key_CursorRight) && x < (SCR_W - SP_W) ) ++x; 
      else if (cpct_isKeyPressed(Key_CursorLeft)  && x > 0              ) --x; 
      if      (cpct_isKeyPressed(Key_CursorUp)    && y > 0              ) --y;
      else if (cpct_isKeyPressed(Key_CursorDown)  && y < (SCR_H - SP_H) ) ++y;
      
      // Get video memory byte for coordinates x, y of the sprite (in bytes)
      pvideomem = cpct_getScreenPtr(CPCT_VMEM_START, x, y);

      // Draw the sprite in the video memory location got from coordinates x, y
      cpct_drawSprite(g_mouse_left, pvideomem, SP_W, SP_H);
      for(i=0; i < WAITLOOPS; ++i);
   }
}

```
screen background is pink
black ends up to be pink
white ends up to be yellow
grey ends up to be purple 

Probably the problem is between the chair and the computer but fails to see where ...
I have to read more this 
http://www.cpcwiki.eu/index.php/Creating_images_for_the_Amstrad

but that would not explain why background is pink ...

Great tool!

**Comment by Arnaud6128** [comment]
Hi,
you convert the palette in hardware values  when it  already is, because you use **hwpalette** argument :
`
$(eval $(call IMG2SPRITES,img/mouse_left.png,0,g,16,32,$(PALETTE),,src/,hwpalette))`

Simply remove this line and it should work :
`cpct_fw2hw     (g_palette, 16); // Convert our palette from firmware to hardware colours `

**Comment by kamelie1706** [comment]
Thx!

There is still something strange, when I go on the right it leaves a dotted line trace .... no issue when moving sprite in all other directions.

I am not sure I am using the cpctelera workflow in the right way to generate my sprites. I need to show the sprite from the top and display it to at least 4 directions (maybe 8). Now I generate 4 images which ends up into 4 .c and 4 .h files.
I can of course copy/paste the whole thing manually into one file and comment the generation from image_conversion but I guess it defeats the whole purpose of the workflow!
What is the correct way?

**Comment by kamelie1706** [comment]
Now that I have cpcwiki forum, topic is more relevant to be discussed there as this is not a bug as such.

**Comment by lronaldo** [comment]
> Thx!
> 
> There is still something strange, when I go on the right it leaves a traces. I use a ugly workaround by "cleaning" the sprite place but that is creating flickering
> 

This is completely normal, and has nothing to do with CPCtelera. Amstrad CPC has a video memory. Painting a sprite is changing this memory: you copy sprite bytes in your binary to video memory. Then, the sprite is shown in the monitor because video memory has been changed. As it is memory, it remains changed until you change it again. If not, it will continue displaying same contents. Your sprite is surrounded by zeros up, right and down, but not left. The left that means, if you move to the left, you overwrite all previous memory contents where the sprite was, except the rightmost column, but that goes unnoticed because that column contains zeros. However, when you move to the right, that does not happen. The leftmost column is left in video memory unchanged, and that is your trace. 

Your problems here are not from CPCtelera. These problems are normal learning problems. You need to learn how things work, not only from the CPCtelera perspective, but also from the Amstrad CPC perspective. CPCtelera is a way to save you time, but it can't save you learning time. That is always requiered. Learning is necessary for comprehension, mastery and for creating better games. That takes time. Just be patient and work on understanding details.

**Comment by kamelie1706** [comment]
sure no problem .. just keep in mind is when you learn you do not know typically where the problem is!

**Comment by lronaldo** [comment]
Of course :). I was just clarifying that this is completely normal. Not criticizing at all. The main point is be patient, go step by step, and you will learn lot of things. We will be glad to help you whenever we can. Just put your concentration on the right spot to learn faster: work on comprehending better, do not suppose that things are from CPCtelera. Most of the time, the right thing to understand is how the Amstrad CPC works, not how CPCtelera works :).

**Comment by kamelie1706** [comment]
Yeah do not take me wrong, your code and cpctelera has been a great way to start coding again. I tried sdcc and my own make but that was a bit too much for a restart!
you can see here 
https://youtu.be/RXvhREW60Cw

I learnt :-D

Gracias Amigo
