### ISSUE TITLE
Possible bug converting multiple palettes 

### ISSUE THREAD

**Issue by cmp102** [lronaldo/cpctelera#114]
On development branch when you generate more than 1 palette using image_conversion.mk, for example:

`$(eval $(call IMG2SP, CONVERT_PALETTE , $(PALETTE_DEFAULT), palette_default ))`
`$(eval $(call IMG2SP, CONVERT_PALETTE , $(PALETTE_2), palette_2 ))`

The second palette has wrong values, It generates an array with length of 32 with de previous palette values first.

A quick fix seems to be clearing the value of  I2SCP_PHW on file cpctelera/cfg/modules/img2sp.mk line 187 with `I2SCP_PHW:=`.

Thank you :)

**Comment by lronaldo** [comment]
Completely right. Thank you for pointing the issue and even figuring out the solution. I've uploaded the patch and now it works as expected.
