### ISSUE TITLE
cpct_drawTileZigZagGrayCode4x8_af missing in header file

### ISSUE THREAD

**Issue by juritobi** [lronaldo/cpctelera#116]
in branch development the function can't be used because " void cpct_drawTileZigZagGrayCode4x8_af (void* pvideomem, void* sprite) __z88dk_callee; " is not listed in "src/sprites/drawTile/drawTile.h".

**Comment by lronaldo** [comment]
Thanks @juritobi. You are completely right. I have also fixed some flaws in the documentation related to this issue.

Everything should be okay by now.
