### ISSUE TITLE
Sprite Mirroring

### ISSUE THREAD

**Issue by AmstradGamer** [lronaldo/cpctelera#12]
I find very interesing beeing able to draw sprites mirrored horizontally or vertically or both.

This would allow to reduce the amount of memory dedicated to sprites.

Thank you.

**Comment by lronaldo** [comment]
New master branch includes horizontal flipping functions. There still are some more flipping techniques waiting to be implemented, but most important ones are now usable.

**Comment by AmstradGamer** [comment]
I have realized that this issue is closed, but only horizontal flipping has been implemented, not vertical. :(

It's not necessary to reopen it, but please take it into account.

Thank you! Horizontal flipping works very well. :)

**Comment by lronaldo** [comment]
Don't worry, man :) It will be taken into account. However, there are functionalities that have greater prioirity now, like compression or casete/disk file I/O. Something has to be prioritized, but everything is important :).
