### ISSUE TITLE
Read Video Memory into variable

### ISSUE THREAD

**Issue by AmstradGamer** [lronaldo/cpctelera#16]
In some situations it would be useful to have a function to read video memory and store its content in a variable, for example to redraw a given zone of the screen quickly only restoring part of it.

I'm thinking in something like: 

**void cpct_readSprite (void\* memory, void\* sprite,  u8 width, u8 height)**

This function should store video memory in the rectangle defined with width & height, at the position indicated by the first pointer, into sprite.

The idea is not having to deal with the video memory format and use memcpy from C.

**Comment by lronaldo** [comment]
Created new branch named `readvideomem` for this feature

**Comment by lronaldo** [comment]
cpct_screenToSprite is available in development branch, as a revision of the original code provided by @Arnaud6128
