### ISSUE TITLE
Not possible to compile on modern (up to date) Linux distros

### ISSUE THREAD

**Issue by sergionexus** [lronaldo/cpctelera#165]
Like the title says, I was "distro hopping" a little and I noticed that I was not able to compile cpctelera on distros like Fedora 37 or Arch Linux, to name a few, but the compilation process was successful on Ubuntu 22.04 and derivatives, but only on version 22.04 maximum, it gives error on 22.10

The error comes when compiling "dskgen". Attached is the corresponding log.
[tool_building.log](https://github.com/lronaldo/cpctelera/files/10695517/tool_building.log)

**Comment by lronaldo** [comment]
Please, do not use master branch, as it is outdated. Use development branch, which is up to date.

**Comment by lronaldo** [comment]
Addition: The DSKGen compile error was fixed previously, but was only pushed to development. Thanks to your report, it has now been added to master. Thanks :)
