### ISSUE TITLE
Configurable Hardware Backbuffer size

### ISSUE THREAD

**Issue by AmstradGamer** [lronaldo/cpctelera#17]
Hello.

As far as I know the fastest way to have a hardware double buffer using only CPCTelera requires us to 
use 2 x 16Kb buffers and switch from one to the other. This is a huge waste of memory on a 464.

It would be very useful if we had a way to configure the backbuffer as a smaller memory area so only the game area of the screen gets updated changing buffers and some memory could be saved while kipping the double buffering benefits.

I know this is doable using techniques outside the current scope of CPCTelera but it would be great supporting them on the library.

Thank you.

**Comment by lronaldo** [comment]
The way you are proposing this, it is not possible. There are 3 ways of having a backbuffer:

 * A software backbuffer, slower, but configurable up to your needs. That is normally implemented on a per-project basis, as requirements are different from project to project. It does not have all the benefits of a proper hardware backbuffer.
 * A full-screen backbuffer, exactly as you can do with CPCtelera. Two copies of the entire screen. This is the fastest way: there is no faster way to implement it. You have to do it at the expense of memory.
 * A partial-screen backbuffer. You can already implement this using CPCtelera, in a similar way of a full-screen backbuffer. However, you need to have split screen, as you have to switch buffers during screen-drawing. The easiest way to implement this is using interrupts.

These are the only 3 ways of implementing a backbuffer as far as I know. If you know a different way to do it, please explain. Or, may be, you are referring to a different technique.

**Comment by AugustoRuiz** [comment]
You may add a fourth one:

Touching the CRTC registers, to change the screen size. By doing so, you
use less memory, but the free memory is not linear (remember the memory
layout of video buffers!).

If your screen size is smaller, so you use only half the memory (8kb each),
you can have both screens in the same 16Kb page, so you save 16Kb...

**Comment by AmstradGamer** [comment]
I was talking about Fran's third option and know I see that it is doable using CPCTelera's interrupts handling options. I should have stopped to think before writting. :)

I understand that that I need to do some calculations to know when to swap buffers knowing the time it takes to the screen to refresh and how often interrupts occur.

I'm sorry I didn't realize this myself.

Thank you!

**Comment by lronaldo** [comment]
Yes, @AugustoRuiz, but that's not a backbuffer technique :). That's a completely different technique and should be treated differently. In fact, overscan (and underscan, that should be this called) is already on the task list, but that's another story ;).

**Comment by AugustoRuiz** [comment]
Well, it's underscan and double-buffer... ;)

**Comment by AmstradGamer** [comment]
A litte of topic:

Is that "task list" public so I can check and no bother you with things you already have planned?

Thank you.

**Comment by AugustoRuiz** [comment]
IMHO, "Bothering" (which I think you haven't) is not a problem. It should
help us noticing how much a task is wanted...

**Comment by lronaldo** [comment]
It's internal, but requests do not bother us. In fact, I prefer to know that some features are demanded. That also helps deciding on priorities :).

Even if you ask something that is aldeady "doable", discussion is always useful. New ideas may arise, or different ways to define the API. In the end, CPCtelera is to be used: every usability improvement, however small, is important :).

**Comment by AmstradGamer** [comment]
OK! If someday I get to bother you, please let me know before it's too late. :)

I'll keep asking for features I could need.

I'll close this issue I try to implement the interrupt based option.

Thanks.
