### ISSUE TITLE
Falta texto en asmlnk.txt

### ISSUE THREAD

**Issue by joaquinferrero** [lronaldo/cpctelera#175]
Falta contenido en el archivo

cpctelera/cpctelera/tools/sdcc-3.6.8-r9946/src/sdas/doc/asmlnk.txt

En concreto, faltan partes de las páginas 1-29 y 1-30.

**Comment by lronaldo** [comment]
El fichero viene así en la distribución de SDCC. En principio, tampoco tiene mucho sentido ocuparse de ello: mejor invertir el tiempo en la nueva distribución de CPCtelera incorporando la última versión de ASZ80 a SDCC.
