### ISSUE TITLE
Sprite blitting into a software backbuffer (or into another sprite)

### ISSUE THREAD

**Issue by Arnaud6128** [lronaldo/cpctelera#18]
In order to create a partial screen double buffer we could copy smaller sprites into larger sprite used for background. 
For exemple i draw all objects into room background buffer and after i draw the buffer to screen.

It could be done in C with cpct_memcpy, but it will be faster in full asm.

**Comment by lronaldo** [comment]
I do not see a better way to copy sprite buffers than cpct_memcpy. Concrete copies of sprites could be copied in concrete manners, but that does not seem useful for the general case. In addition to this, it is not clear that there is much to gain with respect to LDIR (the Z80 instruction used for cpct_memcpy). 

However, if you have concrete cases to illustrate this matter, we may further discuss it.

**Comment by Arnaud6128** [comment]
I have need of this function for two cases in my game :
- To draw sprites without flickering and without full screen double buffer because i want just redraw a part of the screen, and i have not enough memory to have a double buffer (firmware needed)
- To make scroll effect when entering in a new room. I replace old background room progressively with the new room background. I have to do in this way because there's not partial copy of sprite in cpct.

I have a buffer of the size of background room. First i copy room background into the buffer with a simple cpct_memcpy.
After i draw sprites masked of objects anywhere in the room, then i draw my buffer to the screen with cpct_drawSprite.

Here my function (for masked sprites), i hope it help to understand :

pPosX / pPosY : Destination coordinates of sprite destination
pDest : Sprite destination
pdWidth : width of sprite destination

pSprite : Sprite source to be draw into destination sprite
psWidth : width of sprite source
psHeight: height of sprite source

	void DrawSpriteMasked(u8 pPosX, u8 pPosY, u8* pDest, u8 pdWidth, u8 *pSprite, u8 psWidth, u8 psHeight)
	{
		u16 yDest = psHeight;
		u16 rowWidth = psWidth*MASKED;
		pDest += pPosX + pdWidth*pPosY;
		
		while (yDest != 0)
		{
			BlitMasked(pDest, pSprite, psWidth);
			
			pSprite += rowWidth;
			pDest += pdWidth;	
			--yDest;
		}
	}

	void BlitMasked(u8* pDest, u8* pSprite, u8 pWidth)
	{
		u8 byteMask, byteColor;
		u8 count = pWidth;
		u8 *pDestPtr = pDest;

		while (count != 0)
		{
			byteMask = *pSprite++;
			byteColor = *pSprite++;

			*pDestPtr = (*pDestPtr & byteMask) | byteColor;
			++pDestPtr;
			--count;
		}
	}

I also have a function for draw simple sprites into buffer, i have added parameter pBlitWidth to draw partial sprite, i use this function to make scrolling between to room.

	void DrawSprite(u8 pPosX, u8 pPosY, u8* pDest, u8 pdWidth, u8 *pSprite, u8 psWidth, u8 psHeight, u8 pBlitWidth)
	{
		u8 yDest = psHeight;
		pDest += pPosX + pdWidth*pPosY;
	
		while (yDest != 0)
		{
			cpct_memcpy(pDest, pSprite, pBlitWidth);
		
			pSprite += psWidth;
			pDest += pdWidth;		
			--yDest;
		}
	}

Here a link to a question i have asked about optimization of this function : http://www.cpcwiki.eu/forum/programming/partial-masked-sprite-copy-to-another-optimisation/msg113883/#msg113883

**Comment by lronaldo** [comment]
Ok, I understand better what you are doing and what your needs are. What you want to do is blitting masked sprites into a software backbuffer before copying them to the screen. That's not supported right now and is an interesting feature.

I'll change the title of this issue and set it as new feature to be implemented.

Thanks for your collaboration, Arnaud :).

**Comment by Arnaud6128** [comment]
Yes it's exactly that. :)

**Comment by lronaldo** [comment]
@Arnaud6128 I have finally reviewed your contribution and it is now merged into the current development branch. You may check it out and suggest any new contribution if you like. I have redesinged your backbuffer example in order to make it clearer for people not knowing anything about it. It would be also helpful if you make another final revision to the documentation of the functions, in order to see if there is any mistake or something is lacking.

Next thing that would be useful in this group of functions is drawSpriteBlended for Sprite Buffers. It would be very nice to do interesting tricks with software buffers.

Thank you very much for your contribution and your time. I'm sure it will be useful for many people 😄
