### ISSUE TITLE
Sprite draw with AND operation or XOR

### ISSUE THREAD

**Issue by Arnaud6128** [lronaldo/cpctelera#19]
I could be useful to do bit operation in same time that sprite drawing.

In my case it prevent me to have masked sprite to make simple shadow effect (like in zombi with the torchlight effect)

**Comment by lronaldo** [comment]
There is an implementation working now on a parallel branch, including a complete example of use. The new function is called cpct_drawSpriteBlended and lets sprites be drawn using whichever blending function the user wanted (XOR, AND, OR, ADD, ADC, SUB, SBC, LDI or NOP). There you go some links:

- Branch: [compositeDrawing](https://github.com/lronaldo/cpctelera/tree/compositeDrawing)
- Example Code: [Blended Sprites](https://github.com/lronaldo/cpctelera/tree/compositeDrawing/examples/medium/blendedSprites)
- [Youtube Video](https://www.youtube.com/watch?v=Izs5c5657-8)

You may test the example and report any problems/sugestions. This feature is to be merged with master in a short period of time.

**Comment by lronaldo** [comment]
This feature is now tested and included in master branch
