### ISSUE TITLE
Error building CPCtelera examples

### ISSUE THREAD

**Issue by mdoege** [lronaldo/cpctelera#2]
I'm trying to build the latest git version (9d6772b). Running setup.sh on Arch Linux I get:

> Proceeding to build required tools to build and manage CPCtelera and other software for Amstrad CPC (This might take a while, depending on your system):
>>> Building compilation tools:                                     100% [ OK ]
>>> Building cpctelera z80 lib:                                     100% [ OK ]
> Bulding procedure finished. 
> CPCtelera's tools and library are now ready to be used on your system.

>>> Building cpctelera examples:                                    100%

#########################
#########################
##> There was an error building CPCtelera examples. Please, check '/home/martin/git/cpctelera/cpctelera/logs/examples_building.log' for details. Aborting. 

The log file says:

DSK : measureCycles.dsk.tmp
Mode : Import fichier dans Dsk 
Fichier Amsdos : measureCycles.bin
Création automatique d'une en-tête pour le fichier ...
Adresse de chargement : &4000
MEASUREC.BIN : 2 Ko
------------------------------------
âmeasureCycles.dsk.tmpâ -> âmeasureCycles.dskâ
[1;31;49m[measureCycles][1;33;49m Successfully created measureCycles.dsk[0;39;49m
make[2]: Verzeichnis â/home/martin/git/cpctelera/examples/medium/measureCyclesâ wird verlassen
make[2]: Verzeichnis â/home/martin/git/cpctelera/examples/medium/tilesâ wird betreten
/home/martin/git/cpctelera/cpctelera/tools/sdcc-3.4.3/bin/sdcc -I/home/martin/git/cpctelera/cpctelera/src -mz80  -c  src/sprites.c -o  obj/sprites.rel
/home/martin/git/cpctelera/cpctelera/tools/sdcc-3.4.3/bin/sdcc -I/home/martin/git/cpctelera/cpctelera/src -mz80  -c  src/main.c -o  obj/main.rel
[1;31;49m[tiles][1;33;49m Linking binary file[0;39;49m
/home/martin/git/cpctelera/cpctelera/tools/sdcc-3.4.3/bin/sdcc -mz80 --no-std-crt0 -Wl-u --code-loc 0x0100 --data-loc 0 -l/home/martin/git/cpctelera/cpctelera/cpctelera.lib obj/sprites.rel obj/main.rel -o "obj/tiles.ihx"

?ASlink-Warning-Undefined Global '_cpct_drawTileAligned4x4_f' referenced by module 'main'
/home/martin/git/cpctelera/cpctelera/cfg/global_main_makefile.mk:43: die Regel fÃŒr Ziel âobj/tiles.ihxâ scheiterte
make[2]: *** [obj/tiles.ihx] Fehler 1
make[2]: Verzeichnis â/home/martin/git/cpctelera/examples/medium/tilesâ wird verlassen
Makefile:39: die Regel fÃŒr Ziel âallâ scheiterte
make[1]: *** [all] Fehler 2
make[1]: Verzeichnis â/home/martin/git/cpctelera/examples/mediumâ wird verlassen
Makefile:39: die Regel fÃŒr Ziel âallâ scheiterte
make: *** [all] Fehler 2
make: Verzeichnis â/home/martin/git/cpctelera/examplesâ wird verlassen

**Comment by lronaldo** [comment]
Thank you very much for reporting. It seems some old function name that's not updated. I'm checking it right now.

**Comment by lronaldo** [comment]
Solved on commit b45ee5c060d32a685a45942ca9400cf9dd5a88c4

There was 1 file left unadded

**Comment by aggranadoss** [comment]
There was an error building CPCtelera tools. Please, check '/home/.../cpctelera/cpctelera/logs/tool_building.log' for details. Aborting. I dont know how to solve.

**Comment by aggranadoss** [comment]
![errortool_buildinglog](https://user-images.githubusercontent.com/57117040/212494204-dbbe2cf9-fe33-4c22-9b78-122a99686bae.png)
![syslexc](https://user-images.githubusercontent.com/57117040/212494207-6fa3dabd-0172-47cd-858f-b598b9f81856.png)

**Comment by aggranadoss** [comment]
Fixed: Once downloaded the cpctelera, switch to the development branch in git. The video for installation on arch linux is **https://www.youtube.com/watch?v=6Z8pWxTbF0g** Thank you very much for all the material and the support of the community

**Comment by lronaldo** [comment]
@aggranadoss The master branch of CPCtelera is too old and gives too many problems with new SOs and compiler versions. We should move development branch to master and replan branches soon.

Thank you for reporting in any case :)
