### ISSUE TITLE
ScanKeyboard designed to be used on interrupt

### ISSUE THREAD

**Issue by Arnaud6128** [lronaldo/cpctelera#22]
I was using interrupt and i just remember the problem with scankeyboard and your post.

@ronaldo :
I'm adding a new scanKeyboard function to the task list: one specially designed to be used on interrupts, for cases like yours :).

**Comment by lronaldo** [comment]
It was already anotated in our internal todo list, but thank you for caring and remembering. Hope to have time soon for implementing this :)
