### ISSUE TITLE
Update tags for master branch

### ISSUE THREAD

**Issue by dfreniche** [lronaldo/cpctelera#26]
Hi,

Last tag [1.3](https://github.com/lronaldo/cpctelera/tree/v1.3) is from 17 Oct 2015. Maybe it's time to add 1.3.1? :-D

**Comment by lronaldo** [comment]
Well, the plan was to release 1.4. with all the new stuff. I'm finishing an interface for 6-bits arrays and then will start with 1.4 issues (Sprite mirroring, clipping and AND/OR modes).

I'd like to test everything on all systems before relesase.

Do you think an intermediate release is advisable? :)

**Comment by dfreniche** [comment]
Just wanted to raise this point to have the different version correctly tagged as I'll need that to make brew package manager update correctly.

I'll recover the Formula and add cpctelera to brew ASAP (after testing that it compiles fine with Xcode 7.2.1)

**Comment by lronaldo** [comment]
There you go, man. Tag 1.3.2 with latest features (namely cpct_set6Bits and cpct_get6Bits plus updated documentation and a new bitArrays example).
