### ISSUE TITLE
Img2CPC number in file name on two digits for binary generation

### ISSUE THREAD

**Issue by Arnaud6128** [lronaldo/cpctelera#30]
In binary generation when more than 9 files are created is possible to set the file number on two digits ?

It make things easier to process the files in the right generation order.
Thanks

Exemple if generation of 50 files :
```
monster_01.bin
...
monster_50.bin
```

**Comment by lronaldo** [comment]
Is this related to the Img2CPC version included with CPCtelera? Can you elaborate a bit more on the example to better know what you are trying to do?

**Comment by Arnaud6128** [comment]
Yes it's the version in CPCtelera.
The goal is to create sprites that are individualy compressed in one file.

Example:
I have one bitmap (320x10) with all the objects (16x16)

In my batch :
* img2cpc -p config.json -of bin -m 1 -im -t 0 -h 16 -w 16 -o ./output/ objects.png
-> i have twenty files generated
object_1
...
object_20

* the batch take every generated file and compress it to another directory
* another tool take all files and appened all in one file with a specific format

The problem is the batch take the files in the wrong order because
object_10 is before object_2 and the wrong sprite is displayed in game. 

I try to sort the files by time, but it's not enough accurate.

If the files would had the following names, there wouldn't be problem anymore
object_01
...
object_20

 I admit that the Issue is especially for me to simplify my generation :smile:

**Comment by lronaldo** [comment]
I think this functionality should be easy for @AugustoRuiz to add to img2cpc. It's probably a good idea to add it.

However, in the meantime, you may create your own batch file taking this number ideosincrasy into account. Something like:
```
for((i=0;i<20;i++)); do
   processObject "object_${i}"
done
```
That may solve your problem :).

**Comment by AugustoRuiz** [comment]
Will certainly do it, just need some time!

**Comment by lronaldo** [comment]
Already working in master branch
