### ISSUE TITLE
cpct_mkproject syntax error

### ISSUE THREAD

**Issue by AmstradGamer** [lronaldo/cpctelera#32]
This issue is not new, nor important, but I forgot about reporting it before.

When you use cpct_mkproject to create a new project, it works as it should, but a syntax error message is shown related with "expr":

cpct_mkproject test
expr: syntax error

===============================================================
== CPCtelera: Creating new project in test/
===============================================================
> Creating project folder structure... [ OK ]
> Copying files from project templates... [ OK ]
> Configuring project name to: test [ OK ]
> Configuring z80 code load address: 4000 [ OK ]
> Configuring $CPCT_PATH: Using environment variable [ OK ]

===============================================================
== CPCtelera: New project created in test/
===============================================================

This has been tested on OS X.

Regards.

**Comment by lronaldo** [comment]
Can you please test this command on a shell and paste output here?
```
A="Hola mamcae"; B=${A%%[ma]*}; echo $B; echo ${#B}
```

**Comment by dfreniche** [comment]
With bash:
```
[dfreniche@Tesla ~]$ A="Hola mamcae"; B=${A%%[ma]*}; echo $B; echo ${#B}
Hol
3
```

**Comment by AmstradGamer** [comment]
MacBook-Air:~ toni$ A="Hola mamcae"; B=${A%%[ma]*}; echo $B; echo ${#B}
Hol
3

**Comment by lronaldo** [comment]
Thank you, I will use this code to fix the issue :)

**Comment by lronaldo** [comment]
New implementation for the 'containsChars' bash function should solve the issue. Could you please test `cpct_mkproject` again? (Try to include weird characters on your project name to test the script, like _\\/%[](), for instance)
