### ISSUE TITLE
Sprite horizontal flipping using tables

### ISSUE THREAD

**Issue by lronaldo** [lronaldo/cpctelera#33]
Improve horizontal flipping techniques by using memory-aligned flipping tables.

**Comment by lronaldo** [comment]
Functionality is working on `spritemirroring` branch. Still pending documentation before merging with `development`. Relevant commits to look at: f21670d9b4ef73efdc83fc26225bc607d22978a2, 96b43cccbc36f704f7f6d972f1c88a2ca6914315,

**Comment by lronaldo** [comment]
@AmstradGamer You may have missed it due to its new terminology. Function name is `cpct_drawSpriteHFlipMasked_at` (at = aligned table)

**Comment by AmstradGamer** [comment]
Ok! I will try it. I understood it only used the flip table.

**Comment by AmstradGamer** [comment]
It DOES work now. :)

Thank you.
