### ISSUE TITLE
tilemap_hwscroll does not compile because of problem with cpct_tmx2csv

### ISSUE THREAD

**Issue by AmstradGamer** [lronaldo/cpctelera#39]
Hello.

The tilemap_hwscroll example does not compile because cpct_tmx2csv generates an empty array in tilemap.c

```
[tmhwscr] Converting tilemap in img/tilemap.tmx into C-arrays...
cpct_tmx2csv -gh -ci g_tilemap -of src/  img/tilemap.tmx
Generating 'src//tilemap.c'...
Generating 'src//tilemap.h'...
/Users/toni/cpctelera/cpctelera/tools/sdcc-3.5.5/bin/sdcc -I/Users/toni/cpctelera/cpctelera/src -mz80  -c  src/tilemap.c -o  obj/tilemap.rel
src/tilemap.c:12: syntax error: token -> '}' ; column 1
make: *** [obj/tilemap.rel] Error 1
```

This is the content of tilemap.c file:

```
// Generated CSV tilemap from img/tilemap.tmx
const u8 g_tilemap[120*46] = {

};

```
Also, setup.sh doesn't check for this compilation problem as it doesn't complaint about it.

This has been tested on OS X using latest content of the master branch.

Regards.

**Comment by lronaldo** [comment]
I think that latest patch for v1.5 may have solved this issue. Could you verify it, @AmstradGamer, please?

**Comment by AmstradGamer** [comment]
I can confirm that this problem has been solved in v1.5, BUT now there is a problem with the image_conversion in macOS that doesn't appear on Windows. It complains about needing a filename.

So now I can convert TMX files but I can't "cut" images into tiles.

Do you want me to open a new issue with more detail?

**Comment by lronaldo** [comment]
That's a different issue so, please, open a different issue and detail the problem as much as posible.

Thanks :+1:

**Comment by Unbedingt** [comment]
Tengo exactamente el mismo problema.
Tengo la última version del Tiled (1.1.6) en Mac
Existe alguna solución?

```
/Users/toni/cpctelera/cpctelera/tools/sdcc-3.5.5/bin/sdcc -I/Users/toni/cpctelera/cpctelera/src -mz80  -c  src/tilemap.c -o  obj/tilemap.rel
src/tilemap.c:12: syntax error: token -> '}' ; column 1
make: *** [obj/tilemap.rel] Error 1
```
