### ISSUE TITLE
No check with unallowed character in AMSDOS filename

### ISSUE THREAD

**Issue by gryken2014** [lronaldo/cpctelera#4]
Thanks for this pretty impressive work.

1) I have found an issue, with project name and filename in .DSK

- Create a new projet: 
  * cpct_mkproject name_abc
  * cd name_abc
- I keep, the default source
  * make

- All is OK : the dsk file is created : I use with arnold.
- The "cat" command lists the file "name_abc.bin"
- I run "name_abc.bin"
- Then, in emulator, i've got the error message : "Bad command".

2) I have build and run all examples, in cpctelera, without problem.

3) I found a AMSDOS doc, that the underscore character is not allowed.
- All build process, with project "name_abc, run without error, nor warning message.

- So, if there is an unallowed character (from AMSODS point of view) in project name, it stays in filename, created in .DSK.

4 ) Next, I try to create a new project named "name-abc", instead of "name_abc".
- When, I run it, in Arnold, it works great.

5 ) Platform :
- Linux Mageia 4 - x86_64
- Arnold
- cpctelera 1.0.1 

I not sure how to fix this..

**Comment by lronaldo** [comment]
You are right, gryken2014. Thank you for reporting :).

I'm adding some checks to prevent this from happening. You will find a fix for this on the last commit on the master branch :).
