### ISSUE TITLE
EasyTilemaps memory footprint improvement

### ISSUE THREAD

**Issue by AmstradGamer** [lronaldo/cpctelera#41]
Hello.

In my new game I am using EasyTilemaps with a large tileset. I have 320 different 2x4 tiles.
This makes me have a tileset array with 320 pointers to each tile, which uses 640 bytes.

On the other hand, I think it is very common to have, as I have, each tile after the previous one in memory, so theoretically only a pointer to the first tile should be necessary as the next will be 2x4 bytes away and so on, so it is very easy to calculate the position of each tile in memory only using a pointer to the first one.

I know it will propably have a performance impact but I would be very happy if I could have the option to save those 640 bytes.

Thank you.

**Comment by Arnaud6128** [comment]
Effectively too many memory is taken with structure, if we could have a 2D array to keep all tilesets it would make a great  memory improvement.

Here what i think, if the current structure :
```
u8* const g_tileset[120] = { 
	g_tiles_000, g_tiles_001, ....
};

const u8 g_tiles_000[2 * 4] = {
...
};

const u8 g_tiles_001[2 * 4] = {
...
};
```

is replaced with this structure :

```
#define TILES_000	0
#define TILES_001	1
...
#define TILES_119	119
g_tiles[120][2 * 4] = { {...}, {...}, ..., {...} };
```

We don't have to keep the array of pointers. Is right ?

Thanks.

**Comment by AmstradGamer** [comment]
Well, in fact,  having 120 [2*4] consecutive arrays and having a [120][2*4] matrix uses exactly the same amount of memory and it is ordered exactly in the same way. There is no difference. Accessing the data using pointers is normally faster than using indexes, so the point is just not to use a table of pointers.

**Comment by AugustoRuiz** [comment]
You can always use img2cpc and use the /nt to avoid generating the tileset
array...

**Comment by AmstradGamer** [comment]
Of course Augusto, but the CPCTelera requires it for easytilemaps.

**Comment by AugustoRuiz** [comment]
Maybe you could contribute an alternate engine that takes such
requirements, so both alternatives coexist. I think that for learning
purposes, the current implementation is easy to understand. Those advanced
developers that might need to take advance of this alternative would have a
choice :)

**Comment by lronaldo** [comment]
Hi guys,

   Sorry for taking so long to answer. These days are being overwhelming. 

   Thank you all for you contributions and ideas. It's amazing to see the growing amount of proposals to improve CPCtelera. We can make it much better together, for sure :smile:. 

   I will start detailing you the reasons that made me chose this design for easytilemaps, and some insights.

   First of all, @AmstradGamer, take into account that easytilemap functions cannot deal with tilesets greater than 256 tiles-long directly. As you probably already know, tilemaps use 8-bits per tile, so there is no way to address tiles beyond 2^8 scope (at least, not directly). If you need more than 256 tiles, I advise you to create different tilesets and change them previously to drawing different parts.

   Second part: the tileset array. I agree with you in that tileset array takes a great amount of memory. However, there are practical reasons to have chosen this approach in the easytilemaps module. 

   First, it is much faster with the present implementation. Using just an array of 8-byte tiles as you are suggesting is possible, but will make the inner drawing loop ~50% slower with the present implementation. It will require a complete redesign for a faster implementation without a tileset.

  Second, the tileset gives a great deal of flexibility. Rearranging the tileset we can perform effects on the maps: tiles can be replaced, reordered or even scattered (you can place different parts of your tileset at different points in memory). You can have mixed tilesets just mixing up parts of the tileset, no matter where tiles are placed in memory. This flexibility is impossible to achieve with linear arrays of tiles. 

  Having said that, the overall design of CPCtelera is thought for having different coexisting implementations of algorithms. If you need a new version of easytilemaps that prescinds of the tileset array of pointers, it is always possible to add that implementation without removing the preexisting one. That's how I would proceed in this case.

  Regretably, I won't have enough time for that in the near term. I hope to continue CPCtelera development by next month or so. In the meantime, If someone wants to help contributing with a new module for easytilemaps, I will be very happy to add it to the library :smile:.

Thank you, guys :grinning:
