### ISSUE TITLE
Select memory Bank

### ISSUE THREAD

**Issue by Arnaud6128** [lronaldo/cpctelera#42]
Adding functions to select memory bank on CPC 6128 and detect is more than 64kb are available.
It'd help developpers to make program > 64kb easily without writing asm code.

**Comment by AugustoRuiz** [comment]
I have this already developed... I'll upload it.

**Comment by lronaldo** [comment]
We'll try to have this for CPCtelera 1.5. It'd be nice to have a new release for Christmas :smile:

**Comment by Arnaud6128** [comment]
Nice ! A special CPCTelera Christmas edition 😃 

I have updated the issue with the possibility to detect if more than 64kb are available.

**Comment by lronaldo** [comment]
I believe cpct_pageMemory function added by @AugustoRuiz closes this issue. It is now added to CPCtelera 1.4.2.
