### ISSUE TITLE
cpct_img2tileset fails on macOS

### ISSUE THREAD

**Issue by AmstradGamer** [lronaldo/cpctelera#44]
The same works perfectly on Windows:

```
[Test] Converting tilemaps/mountains.bmp into C-arrays...
cpct_img2tileset  -m "0" -bn "mountain" -tw "4" -th "4" -pf {0 26 11 24 1 2 3 6 15 9 18 5 16 23 12 14}  tilemaps/mountains.bmp;
/Users/toni/cpctelera/cpctelera/tools/scripts/cpct_img2tileset: line 243: -1: substring expression < 0
[ ERROR ]: A <filename> parameter is required.
```

**Comment by cpcitor** [comment]
Thanks for reporting. Probably older version of bash. Can you paste the output of `bash --version` ?

**Comment by AmstradGamer** [comment]
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.

Thanks.

**Comment by fidergo-stephane-gourichon** [comment]
Okay. Can you edit /Users/toni/cpctelera/cpctelera/tools/scripts/cpct_img2tileset and at line 243 replace

    NEXT=${NEXT:0:-1}

with

    NEXT=${NEXT:0:$(( ${#NEXT} - 1 ))} # ${NEXT:0:-1} not accepted by bash 3.2.57 on Mac OS X

and tell if things work better?

Also, what is your version of Mac OS X?

**Comment by AmstradGamer** [comment]
Yes, you corrected the problem. Thank you very much.

My OS version is macOS Sierra 10.12.1. The latest one.
