### ISSUE TITLE
Inconsistency between documentation and source code?

### ISSUE THREAD

**Issue by patxoca** [lronaldo/cpctelera#57]
Hi,
newbie here.

I'm trying to build a project that includes:

    .globl cpct_getRandom_mxor_u8_asm

    ...
    call cpct_getRandom_mxor_u8_asm
    ...

but the linker complains about `?ASlink-Warning-Undefined Global 'cpct_getRandom_mxor_u8_asm' referenced by module ''`.

According to [the docs](http://lronaldo.github.io/cpctelera/files/random/cpct_getRandom_mxor_u8-s.html) the assembly call is `call cpct_getRandom_mxor_u8_asm`, but looking at CPCTelera's source code I can't find that function. There's a `cpct_getRandom_mxor_u8` function instead.

Not sure if I'm doing something wrong ...

Best regards

**Comment by lronaldo** [comment]
Hi @patxoca,

   Thanks for reporting this issue. In fact, you are quite right. The label in the code is `cpct_getRandom_mxor_u8` and it should be `cpct_getRandom_mxor_u8_asm`. It seems a copy-paste mistake.

   While it is fixed and included in next release, you may simply use one of the 2 existing labels for the call: `cpct_getRandom_mxor_u8` and `_cpct_getRandom_mxor_u8`.

Cheers!
