### ISSUE TITLE
How to use CPCTelera in a different more general Makefile

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [lronaldo/cpctelera#63]
Hi

I am trying to figure how how to integrate CPCTelera as a CPC target in my general Makefile that compiles my game CROSS CHASE for nearly all 8 bit computers (using multiple tool chains for the 6502 and Z80):
https://github.com/Fabrizio-Caruso/CROSS-CHASE

CPCTelera's Makefile is not clear to me.
I would like call sdcc with the right includes and libs + whatever is needed to generate a cdt and/dsk executable from my own Makefile.

Any info on how to do this?

**Comment by lronaldo** [comment]
Hi @Fabrizio-Caruso 

   CPCtelera is a framework itself. Therefore, what you are trying to do is to adapt a framework to your own framework. That's hard to do. That's not trivial.

   CPCtelera makefiles are structured to be easy and direct to use for the creation of new Amstrad CPC projects. But, of course, they are not thought to be used in any possible situation a developer can imagine, like "docking" its own framework to CPCtelera's. 

   CPCtelera's projects autoconfigure on creation and they call SDCC and link with the library and produce CDT and DSK automatically. It also includes autoconversion utilities for assets that easily integrate in the makefile. Moreover, it can automatically install and launch WinAPE from the command line to ease development steps. 

   The easiest way to use it would be to create a new CPCtelera project and add your C source files to the src/ folder. Then, if you needed to link against your own library, just need to modify corresponding makefile variables on cfg/build_config.mk. It might take a little way to figure out how they work, but not nearly as much as building something similar by your own.

   With respect to your framework using CPCtelera like kind of a "subsystem", that goes far away beyond my scope. I can help you on how CPCtelera works, but I can help you with your system. In fact, I wouldn't advice you on trying that as first step. If I were you, I would try first to create a simple CPCtelera project, compile and run it, then play with it to understand the framework. As a second step, I would try to integrate you code into a CPCtelera project and compile it along with the libraries and things. Finally, and first analyzing if it pays off, I would go for "docking" your system to CPCtelera's. Personally, I don't thing that final step would pay off for a single project, but that's up to you.

   Hope that helps.

**Comment by Fabrizio-Caruso** [comment]
Yes, I know CPCTelera is a whole very powerful framework but I only need sdcc + CPCTelera's libs.
I just need some graphics and sound libs in my own multi-system game that is built with a very simple Makefile that invokes multiple compilers and tools but it does this in a straightforward way.

I do not want to use the whole framework.
I thought it was not so hard to just use CPCTelera's libs outside its own framework.
I thought it was a matter of 
1. invoking sdcc with the right arguments with the right libs and includes
2. invoking whatever tools are necessary to create .cdt and/or .dsk files
but I cannot find much info on how sdcc is invoked if I look at the Makefile.
I must admit I am not an expert in Makefile scripts...

I do not need the rest of the framework for my "universal" 8-bit game.

**Comment by lronaldo** [comment]
Well, If you want to invoke SDCC with the right parameters, you don't even need to go into de Makefiles. If you create one project and launch make you can just look at the command line and see the compilation lines. They have all the information you need for that.

Then, for using CPCtelera library outside its framework, you only need SDCC, the cpctelera.lib file and the header files. You can find all cpctelera header files in the cpctelera/src/ folder, and cpctelera.lib in cpctelera/ folder. (cpctelera.lib its created during setup.sh). 

I understand you idea of "universal" 8-bit game, but can't see any advantage on moving the library and compiler outside. However, my view is limited, as I don't know your framework and/or architecture. In any case, you may do what you think of better for your project, of course.

One additional comment: I saw your post on CPCWiki. Latest cpcrslib.lib won't work with Z88DK because it is a SDCC .lib. Another thing you can also do in CPCtelera framework: with cpct_installrslib command it automatically downloads and installs latest cpcrslib, leaving it ready to be used along with CPCtelera projects.

**Comment by Fabrizio-Caruso** [comment]
Thanks for your suggestions!

Remark: I used Z88DK's version of cpcrslib, which is no longer working because of some changes in Z88DK which have been reverted yesterday. So it may now work with the very latest snapshot.

The idea is: who gets my code can build all the targets once he is installed the compilers and some tools to convert the binary files into the good format (.cas, .wav, .cdt. etc.)
I would like to provide a single Makefile to build my game for ALL targets for whoever gets my code without the need to use different Makefiles or scripts.
For example if you get my code you simply do:
make c64 -> you build the c64 version of the game (for this you only need CC65)
make spectrum_48k -> you build the Spectrum version (you need Z88DK)

If I manage to use cpctelera (cpcrslib is the alternative),
I will either get your permission to use provide lib with my code (free and open source) or I will have to provide info on how to extract it from the framework.

**Comment by Fabrizio-Caruso** [comment]
Remark: I am not porting my game to 100 different targets.
I am writing my game with generic code that is agnostic of the hardware.
Then I use the same code using conio.h to implement input/output for as many targets as possible.
When this is too slow or when I want to add better graphics, I implement specific input/output for a target. 
The preprocessor will do the rest.

**Comment by Fabrizio-Caruso** [comment]
Thanks for the support! I will try my best and let you know if I am able to integrate your lib in my code.

**Comment by lronaldo** [comment]
Hi @Fabrizio-Caruso ,

   I wish you luck with your project, and hope that you accomplish your goal and make a game for multiple Z80 targets. Hope that some of the things we have commented here become useful for you at any point in development. 

  I am personally sorry for not having enough time to help you more. However, if you have any doubts and I can find the time for helping you solve them, it will be a pleasure for me.

  Good luck and good job :)
