### ISSUE TITLE
Sprite Vertical Flipping

### ISSUE THREAD

**Issue by AmstradGamer** [lronaldo/cpctelera#67]
Hello.

As requested on Issue #12 it would be very usefull having functions to vertically flip sprites, similar to the ones available for horizontal flipping.

It would be a huge memory save in the new game I am working on. :)

I tried to do it myself, based on cpct_hflipSpriteM0, but my asm is still to poor to achive that.

Thank you.

**Comment by lronaldo** [comment]
Hi, @AmstradGamer ,

   I assume that what you really need is something like cpct_drawSpriteVFlip. That would be drawing a sprite bottom-to-top in order to display it vertically flipped, but without modifying your original sprite buffer. Flipping an sprite in-place would also have some utilities, but is going to be probably slower most of the time for games.

    Instead of using cpct_hflipSpriteM0, it's better to start out from cpct_drawSprite, as there is no need for pixel-byte inversion when flipping only sprite-lines.

    Anyway, this task is already on the list for next release, so it will be addressed soon :)

**Comment by lronaldo** [comment]
@AmstradGamer check commit f7bf3e08d87ec24e2903fe54fc431364cf46d632 in development branch. It contains initial implementation for cpct_drawSpriteVFlip. Documentation is still pending and a function to calculate a pointer to the bottom-left corner of the sprite in video memory is also required (as drawing happens bottom-to-top)

**Comment by AmstradGamer** [comment]
It works perfectly. Sorry for not being able to test sooner and thank you very much for your help.

**Comment by AmstradGamer** [comment]
Now, it would be great having a function that uses transparency tables... :)

**Comment by lronaldo** [comment]
Commit 08a5b25c18b898d8c989aaf87ce4cebedb03453c at development branch has now merged current implementations for `cpct_drawSpriteVFlipMasked` and `cpct_drawSpriteVFlipMasked_at`. Both functions have been tested and seem to be perfectly working. In fact, both of them are a little bit faster than their non-VFlip counterparts.

@AmstradGamer Could you please test the functions and report if they work on production conditions?

**Comment by AmstradGamer** [comment]
Sure. I will test them this afternoon and let you know how it worked.

**Comment by AmstradGamer** [comment]
I can confirm that cpct_drawSpriteVFlipMasked_at works perfectly. I will test the other one as soon as I can.

Thank you!

**Comment by lronaldo** [comment]
Really nice to hear that. Hope it helps on your next project. If you can test the other functions and give feedback, that would be really appreciated :smile:
