### ISSUE TITLE
cpct_memset_f64 and _f8 Interrupt-friendly version

### ISSUE THREAD

**Issue by Arnaud6128** [lronaldo/cpctelera#72]
As discuted about _Gauntlet 2_ clear screen method :
http://www.cpcwiki.eu/forum/programming/(cpctelera)-trying-to-make-a-gauntlet-like-engine/

Add new functions **cpct_memset_f64_i and cpct_memset_f8_i** that reenable interrupt at each end of chuncks. 

In this way the interrupts could be used while keeping fast mem fill functions (with a little loss of speed).

**Comment by lronaldo** [comment]
I've renamed the title to interrupt-friendly, as I think it describes more accurately what these functions would achieve. 

As you are already working on them, you may continue and contribute them when they become ready. They will be useful for many developers.

**Comment by lronaldo** [comment]
cpct_memset_f64_i was reviewed and integrated on commit 4a04e3c99aa7c815f707ec5c10095005e2c4f0de, while cpct_memset_f8_i was discarded because standard cpct_memset offers better performance (speed gain for moving 8 bytes at a time is lost when saving/restoring SP)
