### ISSUE TITLE
Problem running setup.sh with mktemp command in MacOS High Sierra

### ISSUE THREAD

**Issue by pedgarcia** [lronaldo/cpctelera#78]
When I run setup.sh in my Mac I noticed that mktemp commands were returning `mktemp: too few X's in template 'tmp'` making the setup to fail.

After some digging I managed to workaround the problem changing the createTempFile function as below:

```
function createTempFile {
  if checkSystem "osx"; then
    mktemp -t tmp.XXXXXX
  else
    mktemp
  fi
}
```

Not sure if that is the correct solution for the problem, but might help other Mac users.

Paulo Garcia
https://www.vintageisthenewold.com

**Comment by lronaldo** [comment]
Thank you very much @pedgarcia and @fidergo-stephane-gourichon for your report and analysis. I have been reading and seems quite curious that mktemp was working without template (XXXXX) taking into account that OSX inherits from BSD. When i introduced the `mktemp -t tmp`, i read and found it to be the default solution for OSX. However, i think that @fidergo-stephane-gourichon is right and the proper solution is using the template. It should work on all OSX, but i never feel sure, 'cause i'm not on the OSX world. 

I'm going to accept @fidergo-stephane-gourichon pull request and add it to master. Could you please test this solution on older OSXs @pedgarcia @dfreniche @fidergo-stephane-gourichon ?

Thank you again for your collaboration :smile:
