### ISSUE TITLE
error building development branch

### ISSUE THREAD

**Issue by johnlobo** [lronaldo/cpctelera#82]
Setup.sh stops during the section "building compilation tools" at 0%.. 

"unrecoverable error"

Trace from the log 
gcc  obj/cpc2cdt.o  obj/tinytape.o -o bin/cpc2cdt -O3 -fsigned-char -Wall -DUNIX -pedantic
Undefined symbols for architecture x86_64:
  "_write_byte", referenced from:
      _creatblock in tinytape.o
      _char2block in tinytape.o
      _closeblock in tinytape.o
      _tiny_tape_gen in tinytape.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [bin/cpc2cdt] Error 1
make: *** [cpc2cdt] Error 2

Operating System: MacOs High Sierra ver.10.13.6

**Comment by lronaldo** [comment]
It is quite bizarre that clang complaints about not finding symbols for a given architecture, taking into account that those symbols have been already built by itself: creatblock, char2block, etc are functions defined inside tinytape.c. They have nothing special: they are normal C functions. 

As I do not have an OSX High Sierra, I cannot test it by myself. Could you please do these steps and report results?

1. Enter cpctelera/tools/cpc2cdt
2. type in `make cleanall && make`. Report result
3. If result is same. Edit `Makefile` and remove `-DUNIX` from compilation flags.
4. repeat step 2 and report result.

**Comment by johnlobo** [comment]
- up tp step 2... same result...

make cleanall && make
Removing obj/ intermediate folder...
Removing bin/cpc2cdt...
Creating obj/ intermediate folder...
gcc -O3 -fsigned-char -Wall -DUNIX -pedantic src/cpc2cdt.c -c -o obj/cpc2cdt.o
gcc -O3 -fsigned-char -Wall -DUNIX -pedantic src/tinytape.c -c -o obj/tinytape.o
gcc  obj/cpc2cdt.o  obj/tinytape.o -o bin/cpc2cdt -O3 -fsigned-char -Wall -DUNIX -pedantic
Undefined symbols for architecture x86_64:
  "_write_byte", referenced from:
      _creatblock in tinytape.o
      _char2block in tinytape.o
      _closeblock in tinytape.o
      _tiny_tape_gen in tinytape.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/cpc2cdt] Error 1

- and removing -DUNIX... same reesult...

make cleanall && make
Removing obj/ intermediate folder...
Removing bin/cpc2cdt...
Creating obj/ intermediate folder...
gcc -O3 -fsigned-char -Wall -pedantic src/cpc2cdt.c -c -o obj/cpc2cdt.o
gcc -O3 -fsigned-char -Wall -pedantic src/tinytape.c -c -o obj/tinytape.o
gcc  obj/cpc2cdt.o  obj/tinytape.o -o bin/cpc2cdt -O3 -fsigned-char -Wall -pedantic
Undefined symbols for architecture x86_64:
  "_write_byte", referenced from:
      _creatblock in tinytape.o
      _char2block in tinytape.o
      _closeblock in tinytape.o
      _tiny_tape_gen in tinytape.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [bin/cpc2cdt] Error 1

**Comment by lronaldo** [comment]
Thanks @cpcitor for testing. In fact, it also happens on Manjaro, as the problem is not OS related, but clang's. It seems that clang treatment of inline functions is different than gcc's. While inline keyword is a hint for optimization to gcc, clang expects 2 versions of the same function (one inlined and another non-inlined). That was the reason of undefined functions: it was not finding non-inlined versions.

Latest commit should fix the issue. Please, @johnlobo , could you pull latest commit and test it again?

Thank you :)

**Comment by johnlobo** [comment]
It works now... but it stops at 100% with another unrecoverable error related with clang...

[ToolMaker::c_scripts] Building  tmx2data...
*****************************************************************
*** COMPILANDO LIBRERIA: tmxlite

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C libs/tmxlite/
mkdir -p obj obj/detail
g++ -std=c++14 -O4 -Werror -Wall -fsigned-char -static -pedantic -o obj/FreeFuncs.o -c -Isrc -Iinclude src/FreeFuncs.cpp
clang: error: -O4 is equivalent to -O3 [-Werror,-Wdeprecated]
make[3]: *** [obj/FreeFuncs.o] Error 1
make[2]: *** [libs/tmxlite/bin/tmxlite.a] Error 2
make[1]: *** [tmx2data] Error 2
make: *** [scripts/c_scripts] Error 2

**Comment by lronaldo** [comment]
So many complaints from `clang` for minor details...

Latest changes should make everything compile now. I tested them using clang and everything worked for me.

**Comment by johnlobo** [comment]
It worked!!

Cpctelera 1.5 dev built in MacOs High Sierra ver.10.13.6.

Good job, thank you.
