### ISSUE TITLE
.aks files not recognised as valid AKS/STK file

### ISSUE THREAD

**Issue by davidasta** [lronaldo/cpctelera#83]
When compiling (make) I get the error: _is not a valid AKS/STK file. Please check it with Arkos/Starkos traker._, but I can open them with AKS.

I have tested with the examples/medium/arkosAudio and it also fails:

```
#########################
## UNRECOVERABLE ERROR ##
#########################
##> FILE 'music/molusk.aks' is not a valid AKS/STK file. Please check it with Arkos/Starkos traker.

make: *** [cfg/music_conversion.mk:58: src/molusk.s] Error 13
```

**Comment by lronaldo** [comment]
What are you exactly compiling when you get this error?

**Comment by davidasta** [comment]
Updated version solves the problems. Thank!

**Comment by lronaldo** [comment]
Nice! One more thing tested and working. Thank you, @davidasta ! :smiley:
