### ISSUE TITLE
cpct_drawStringM0 missing paramenters?

### ISSUE THREAD

**Issue by davidasta** [lronaldo/cpctelera#84]
When compiling a source that uses _cpct_drawStringM0_ I get _error 101: too many parameters_

I've compared _cpct_drawStringM0.asm_ with _cpct_drawStringM0.s_ from 1.4 and I've seen that the new version in development has dropped the last 2 parameters (fg_pen and bg_pen).

After removing the last two parameters on my code, it compiles without issues.

I don't know if this is intentional. If so, this would make 1.5 not compatible with 1.4 as programs written for 1.4 won't compile if using such call.

**Comment by lronaldo** [comment]
This is completely intentional. drawString/drawChar functions have been completely redesigned and reimplemented. They are faster and much more flexible. 

Please, read help on functions to know how they work. Open docs/index.html with your browser and you will have 1.5. updated local help.
