### ISSUE TITLE
Launch of RVM2 from CPCTelera v1.5 fails with long project names

### ISSUE THREAD

**Issue by dfreniche** [lronaldo/cpctelera#92]
To reproduce:

- create a project with a long name, like `cpct_mkproject hyphen-name`
- `cd hyphen-name`
- `make && cpct_rvm hyphen-name.dsk`

This will throw a `Bad Command` inside RVM 2. Because the file in disc is called `hyphen-n.bin`, but CPCTelera tries to launch it with full name, as appears in console:

```
Launching RetroVirtualMachine V2...
Machine:  cpc664
DSK:      hyphen-name.dsk
Command:  RUN"hyphen-name"
```

**Comment by lronaldo** [comment]
Nice suggestion, @dfreniche. I think commit e5450cd fixes the problem by limiting automatic execution to 8-character long filenames at most. 

Please, remember that for other uses you have `-r` modifier, to run exactly what you wanted.
