### ISSUE TITLE
git clone then setup.sh fails on cygwin

### ISSUE THREAD

**Issue by cpcitor** [lronaldo/cpctelera#94]
Reported by asertus on http://www.cpcwiki.eu/forum/programming/cpctelera-1-0-amstrad-cpc-game-development-library-official-release/350/#msg177124

Problem with development branch.

> Hi, these holidays I have decided to try out the new release, 1.5, but when I try to run setup.sh, I get these errors:
>
>     ./setup.sh: línea 19: $'\r': no se encontró la orden
>     ./setup.sh: línea 27: $'\r': no se encontró la orden
>     ./setup.sh: línea 33: $'\r': no se encontró la orden
>     : No such file or directory/User/cpctelera
>     ./setup.sh: línea 36: $'\r': no se encontró la orden
>     ./setup.sh: línea 39: error sintáctico cerca del elemento inesperado `$'{\r''
>     '/setup.sh: línea 39: `function usage {
>
> It is in cygwin, and previous version 1.4.2 works perfectly fine. Does anyone else have this problem?

This is because by default, git conforms to the platform linefeed (CRLF on Windows). But bash expects Unix linefeeds (LF).

**Comment by lronaldo** [comment]
This is a known problem, and is not only because git by default conforms to Windows, but because asertus is executing the version of git installed in Windows, not in cygwin. I give an answer in the forum and copy it here for convenient reference:

> This is not a CPCtelera problem, but a problem with the tools installed in your system. Many users have experienced same before and has already been addressed many times.
>
> The problem is that cygwin includes tools in your Windows PATH, and you are using Windows GIT instead of cygwin's. Windows GIT by default download files and applies Windows CRLF line ending. This ruins all bash scripts included in CPCtelera: when bash tries to execute any one of them, it fails due to line ending.
>
> The problem is as easy to solve as installing GIT under Cygwin and using Cygwin's instead of Windows'. You could also change line ending policy in your Windows GIT installation, but I usually prefer not to do that.
>
> The only thing CPCtelera can do about this is adverting you in some sense, but CPCtelera cannot prevent you from using different, not properly configured, tools in your system.

**Comment by cpcitor** [comment]
Actually fixed in #95, provided that the git version used is at least 2.10 .
